- alias: "Front Porch Dusk"
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
    service: switch.turn_on
    entity_id: switch.porch_switch

- alias: "Tell the family it's 7:05"
  trigger:
    platform: time
    # Military time format.
    at: '07:05:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: tts.google_say
    entity_id: media_player.kitchen_home
    data:
        message: 'Hello. I just wanted to let you know that it is 7:05.'

- alias: "Tell the family it's 7:09"
  trigger:
    platform: time
    # Military time format.
    at: '07:09:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: tts.google_say
    entity_id: media_player.kitchen_home
    data:
      message: 'Hey! It is seven oh nine! Better get a move on!'

- alias: "Tell the family it's 7:10"
  trigger:
    platform: time
    # Military time format.
    at: '07:10:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.master_bedroom_speaker
        volume_level: 0.75
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen_home
        volume_level: 0.75
    - service: media_player.play_media
      data:
        entity_id: media_player.smart_speakers
        media_content_id: !secret bell_mp3
        media_content_type: audio/mp3
    - delay: 0:00:15   
    - service: tts.google_say
      entity_id: media_player.smart_speakers
      data:
        message: "It is 7:10, and time to leave. Have a good day!"

- alias: "Pushbullet Test"
  initial_state: False
  trigger:
    platform: time
    at: '08:45:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: notify.pushy
    data:
      message: "What does the icon look like?"
      title: "What Icon?"
      data:
        target: "channel/opoazrrvvv"

- alias: "Bathroom Lights Auto"
  trigger:
    platform: state
    entity_id: sensor.bathroom_door
    to: "open"
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_switch
- alias: "Midnight"
  trigger:
    platform: time
    at: '00:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.lights_and_switches

- alias: "Away Mode"
  trigger:
    platform: state
    entity_id: binary_sensor.anyone_home
    to: 'off'
  action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: 'on'
    - service: homeassistant.turn_off
      entity_id: group.away_mode_off

- alias: "Home Mode"
  trigger:
    platform: state
    entity_id: binary_sensor.anyone_home
    to: 'on'
  action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: 'off'

- alias: "Bedroom No Motion"
  trigger:
    platform: state
    entity_id: sensor.bedroom_motion
    to: 'inactive'
    for:
      minutes: 10
  action:
    service: switch.turn_off
    entity_id: switch.bedroom_switch

- alias: "HTML5 Push Test"
  initial_state: False
  trigger:
    platform: state
    entity_id: sensor.bathroom_door
    to: 'open'
  action:
    service: notify.html5
    data:
      message: "Bathroom door open"
      target: "Daryl's XL"
      data:
        actions:
          - action: "button_on"
            title: "Lights On"
            icon: "/local/icons/lightbulb-on_hab.png"
          - action: "button_off"
            title: "Lights Off"
            icon: "/local/icons/lightbulb_hab.png"

- alias: "Porch On via HTML5"
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
     action: button_on
  action:
    service: switch.turn_on
    entity_id: switch.porch_switch

- alias: "Porch Off via HTML5"
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
     action: button_off
  action:
    service: switch.turn_off
    entity_id: switch.porch_switch

- alias: "Tell Daryl when Megan gets home"
  trigger:
    platform: state
    entity_id: binary_sensor.megan_home
    to: 'on'
  action:
    service: notify.html5
    data:
      message: "safe and sound"
      title: "Megan arrived home"
      target: "Daryl's XL"

- alias: "Welcome Daryl home"
  trigger:
    platform: state
    entity_id: binary_sensor.daryl_home
    to: 'on'
  action:
    service: notify.html5
    data:
      message: "Alert megan?"
      title: "Welcome home!"
      target: "Daryl's XL"
      data:
        actions:
          - action: "tell_her"
            title: "Sure..."
            icon: "/local/icons/human-female_hab.png"

- alias: "Option to tell Megan Daryl is home"
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
     action: tell_her
  action:
    service: notify.html5
    data:
      message: "Safe and sound!"
      title: "Daryl arrived home"
      target: "Megan's XL"