- alias: "Front Porch Dusk"
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
    service: switch.turn_on
    entity_id: switch.porch_switch

- alias: "Tell the family it's 7:05"
  trigger:
    platform: time
    # Military time format.
    at: '07:05:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: tts.google_say
    entity_id: media_player.kitchen_home
    data:
        message: 'Hello. I just wanted to let you know that it is 7:05.'

- alias: "Tell the family it's 7:09"
  trigger:
    platform: time
    # Military time format.
    at: '07:09:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: tts.google_say
    entity_id: media_player.kitchen_home
    data:
      message: 'Hey! It is seven oh nine! Better get a move on!'

- alias: "Tell the family it's 7:10"
  trigger:
    platform: time
    # Military time format.
    at: '07:10:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.master_bedroom_speaker
        volume_level: 0.75
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen_home
        volume_level: 0.75
    - service: media_player.play_media
      data:
        entity_id: media_player.smart_speakers
        media_content_id: /local/audio/school_bell.mp3
        media_content_type: audio/mp3
    - delay: 0:00:15   
    - service: tts.google_say
      entity_id: media_player.smart_speakers
      data:
        message: "It is 7:10, and time to leave. Have a good day!"

- alias: "Pushbullet Test"
  trigger:
    platform: time
    at: '08:45:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: notify.pushy
    data:
      message: "It is 8:40 on a weekday, except Friday!"
      title: "Shouldn't fire on Fridays!"
      data:
        file_url:  https://cdn.pixabay.com/photo/2014/06/03/19/38/test-361512_960_720.jpg

- alias: "Bathroom Lights Auto"
  trigger:
    platform: state
    entity_id: sensor.bathroom_door
    to: "open"
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_switch
- alias: "Midnight"
  trigger:
    platform: time
    at: '00:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.lights_and_switches

- alias: "Anyone Home"
  trigger:
    platform: state
    entity_id: device_tracker.mixpix405_daryl_pixel_xl, device_tracker.mixpix405_megans_xl
    to: "home"
    # for:
      # minutes: 10
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.anyone_home