homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 732
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml


# Includes for better organization
group: !include groups.yaml
automation: !include_dir_list automations
script: !include scripts.yaml
zone: !include zones.yaml
camera: !include cameras.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
binary_sensor: !include binary_sensors.yaml
scene: !include scenes.yaml
device_tracker: !include device_trackers.yaml
notify: !include notifiers.yaml
frontend: !include frontend.yaml
history_graph: !include history_graphs.yaml
cover: !include covers.yaml
media_player: !include media_players.yaml
nest: !include nest.yaml

updater: # Checks for available updates
discovery: # Discover some devices automatically
history: # Enables support for tracking state changes over time
config: # Enables configuration UI
logbook: # View all events in a logbook
map: # Enables a map showing the location of tracked devices
sun: # for sunset/sunrise automations, etc

panel_iframe: # Adds links in sidebar to include helpful resources
  configurator: # For Configurator add-on | web-based config editing
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url
  ide: # For IDE add-on | more robust web-based config editing
    title: IDE
    icon: mdi:code-braces
    url: !secret ide_url
  terminal: # For Terminal add-on | web-based hass.io terminal
    title: Terminal
    icon: mdi:console
    url: !secret terminal_url


http: # Enables and configures the web interface
  api_password: !secret api_password
  trusted_networks:
    - 127.0.0.1
    - 10.0.0.0/24
  base_url: !secret base_url_secret
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

recorder: # Database management
  purge_interval: 1
  purge_keep_days: 7

tts: # Text to speech engine selection
  - platform: google

zwave: # Enables z-wave and tells Hass what USB to use
  usb_path: /dev/ttyACM0

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_user
  password: !secret mqtt_pass
  # discovery: true
  # discovery_prefix: homeassistant

google: # For Google Calendar integration
  client_id: !secret google_client_id
  client_secret: !secret google_secret

google_assistant:
  project_id: !secret gass_project_id
  client_id: !secret gass_client_id
  access_token: !secret gass_token
  agent_user_id: !secret gass_agent_userid
  api_key: !secret gass_api_key
  exposed_domains:
    - switch
    - light
    - cover
  entity_config:
    switch.garage_daryl_switch:
      expose: false
    switch.garage_megan_switch:
      expose: false
    switch.bathroom_switch:
      aliases:
        - "Bathroom Lights"
    light.peq_lamp:
      aliases:
        - "Daryl's Bedside Lamp"
    switch.porch_switch:
      aliases:
        - "Porch Light"