- platform: mqtt
  name: "Peq Lamp"
  state_topic: "smartthings/PEQ Outlet/switch/state"
  command_topic: "smartthings/PEQ Outlet/switch/cmd"
  brightness_state_topic: "smartthings/PEQ Outlet/level/state"
  brightness_command_topic: "smartthings/PEQ Outlet/level/cmd"
  brightness_scale: 100
  payload_on: "on"
  payload_off: "off"
  retain: true