- platform: darksky
  api_key: !secret darksky_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - precip_intensity_max
    - uv_index

- platform: plex
  host: !secret htpc_ip
  
- platform: ups
  name: "UPS My Choice"
  username: !secret ups_user
  password: !secret ups_pass

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: google_wifi

- platform: transmission
  host: !secret htpc_ip
  port: 428
  username: !secret transmission_user
  password: !secret transmission_pass
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'

- platform: mqtt
  state_topic: "owntracks/mixpix405/daryl_pixel_xl"
  name: "Daryl's Battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: mqtt
  state_topic: "owntracks/mixpix405/megans_xl"
  name: "Megan's Battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: ipv4_address
    - type: processor_use
    - type: last_boot
    - type: since_last_boot

- platform: mqtt
  state_topic: "smartthings/PEQ Motion Sensor/temperature/state"
  name: "Bedroom Temp"
  unit_of_measurement: "°F"

- platform: mqtt
  state_topic: "smartthings/PEQ Door Sensor/temperature/state"
  name: "Bathroom Temp"
  unit_of_measurement: "°F"

- platform: mqtt
  name: "Bedroom Motion"
  state_topic: "smartthings/PEQ Motion Sensor/motion/state"
  payload_on: "active"
  payload_off: "inactive"
  device_class: "motion"

- platform: mqtt
  name: "Bathroom Door"
  state_topic: "smartthings/PEQ Door Sensor/contact/state"
  payload_on: "open"
  payload_off: "closed"
  device_class: "opening"

- platform: cert_expiry
  host: !secret duck_domain
  port: !secret duck_port
  name: "SSL Cert"