- platform: darksky
  api_key: !secret darksky_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_type
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - precip_intensity_max
    - uv_index

- platform: plex
  host: !secret htpc_ip
  
- platform: ups
  name: "UPS My Choice"
  username: !secret ups_user
  password: !secret ups_pass

- platform: speedtest
  minute: 0
  hour:
    - 0
    - 4
    - 8
    - 12
    - 16
    - 20
  monitored_conditions:
    - ping
    - download
    - upload

- platform: google_wifi

- platform: transmission
  host: !secret htpc_ip
  port: 428
  username: !secret transmission_user
  password: !secret transmission_pass
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'

- platform: mqtt
  state_topic: "owntracks/mixpix405/daryl_pixel_xl"
  name: "Daryl's Battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: mqtt
  state_topic: "owntracks/mixpix405/megans_xl"
  name: "Megan's Battery"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: ipv4_address
    - type: processor_use
    - type: last_boot
    - type: since_last_boot

- platform: mqtt
  state_topic: "smartthings/PEQ Motion Sensor/temperature/state"
  name: "Bedroom Temp"
  unit_of_measurement: "°F"

- platform: mqtt
  state_topic: "smartthings/PEQ Door Sensor/temperature/state"
  name: "Bathroom Temp"
  unit_of_measurement: "°F"

- platform: mqtt
  name: "Bedroom Motion"
  state_topic: "smartthings/PEQ Motion Sensor/motion/state"
  payload_on: "active"
  payload_off: "inactive"
  device_class: "motion"

- platform: mqtt
  name: "Bathroom Door"
  state_topic: "smartthings/PEQ Door Sensor/contact/state"
  payload_on: "open"
  payload_off: "closed"
  device_class: "opening"

- platform: cert_expiry
  host: !secret duck_domain
  port: !secret duck_port
  name: "SSL Cert"

- platform: xbox_live
  api_key: !secret xboxapi_key
  xuid:
    - !secret xbox_uid

- platform: google_travel_time
  name: "Time to Home for Daryl"
  api_key: !secret google_api_key
  origin: device_tracker.mixpix405_daryl_pixel_xl
  destination: zone.home

- platform: google_travel_time
  name: "Time to Home for Megan"
  api_key: !secret google_api_key
  origin: device_tracker.mixpix405_megans_xl
  destination: zone.home

#############
# Templates #
#############
- platform: template
  sensors:
    htpc:
      friendly_name: "HTPC"
      value_template: "{% if is_state('device_tracker.htpclan', 'home') %}Online{% else %}offline{% endif %}"
    ghome_kitchen:
      friendly_name: "GHome Kitchen"
      value_template: "{% if is_state('device_tracker.googlehomelan', 'home') %}Online{% else %}offline{% endif %}"
    range_extender:
      friendly_name: "Range Extender"
      value_template: "{% if is_state('device_tracker.tlwa855relan', 'home') %}Online{% else %}offline{% endif %}"
    ghome_mini_bedroom:
      friendly_name: "GHome Mini (Bedroom)"
      value_template: "{% if is_state('device_tracker.e4f0421cb224', 'home') %}Online{% else %}offline{% endif %}"
    xbox_one:
      friendly_name: "XBOne"
      value_template: "{% if is_state('device_tracker.xboxonelan', 'home') %}Online{% else %}offline{% endif %}"
    st_hub:
      friendly_name: "SmartThings Hub"
      value_template: "{% if is_state('device_tracker.st24fd5b00000037a4lan', 'home') %}Online{% else %}offline{% endif %}"
    sawyer_tablet:
      friendly_name: "Sawyer's Tablet"
      value_template: "{% if is_state('device_tracker.androidea8e397ef27b1c0elan', 'home') %}Online{% else %}offline{% endif %}"
    cast_bedroom:
      friendly_name: "Bedroom Chromecast"
      value_template: "{% if is_state('device_tracker.6cadf82677a2', 'home') %}Online{% else %}offline{% endif %}"
    nest:
      friendly_name: "Nest Thermostat"
      value_template: "{% if is_state('device_tracker.09aa01ac25160s7klan', 'home') %}Online{% else %}offline{% endif %}"
    bathroom_door_status:
      friendly_name: "Bathroom Door"
      value_template: "{% if is_state('sensor.bathroom_door', 'open') %}open{% else %}closed{% endif %}"
      icon_template: "{% if is_state('sensor.bathroom_door', 'open') %}mdi:door-open{% else %}mdi:door-closed{% endif %}"
    daryl_charging:
      friendly_name: "Daryl Charging"
      value_template: "{% if is_state('binary_sensor.daryl_charging', 'on') %}Charging{% else %}Not Charging{% endif %}"
      icon_template: "{% if is_state('binary_sensor.daryl_charging', 'on') %}mdi:power-plug{% else %}mdi:power-plug-off{% endif %}"
    megan_charging:
      friendly_name: "Megan Charging"
      value_template: "{% if is_state('binary_sensor.megan_charging', 'on') %}Charging{% else %}Not Charging{% endif %}"
      icon_template: "{% if is_state('binary_sensor.megan_charging', 'on') %}mdi:power-plug{% else %}mdi:power-plug-off{% endif %}"
    daryl_xl_nmap:
      friendly_name: "Daryl's XL"
      value_template: "{% if is_state('device_tracker.404e36256a50', 'home') %}Online{% else %}offline{% endif %}"
    daryl_watch:
      friendly_name: "Daryl's Watch"
      value_template: "{% if is_state('device_tracker.android5486ce199fee9d90lan', 'home') %}Online{% else %}offline{% endif %}"
    megan_explorer:
      friendly_name: "Megan's Explorer"
      value_template: "{% if is_state('device_tracker.megan_explorer', 'home') %}Online{% else %}offline{% endif %}"
    retropie:
      friendly_name: "RetroPie"
      value_template: "{% if is_state('device_tracker.retropielan', 'home') %}Online{% else %}offline{% endif %}"
    megan_xl_nmap:
      friendly_name: "Megan's XL"
      value_template: "{% if is_state('device_tracker.ac37434dee93', 'home') %}Online{% else %}offline{% endif %}"
    dat_dongle:
      friendly_name: "Dat Dongle"
      value_template: "{% if is_state('device_tracker.chromecastlan', 'home') %}Online{% else %}offline{% endif %}"
    daryl_laptop:
      friendly_name: "Daryl's Laptop"
      value_template: "{% if is_state('device_tracker.darylt540plan', 'home') %}Online{% else %}offline{% endif %}"
    daryls_battery_dyn:
      friendly_name: "Daryl's XL"
      unit_of_measurement: "%"
      value_template: "{{states.sensor.daryls_battery.state}}"
      icon_template: "{%- if states.sensor.daryls_battery.state >= '95' %}mdi:battery{%- elif states.sensor.daryls_battery.state == '100' %}mdi:battery{%- elif states.sensor.daryls_battery.state <= '15' %}mdi:battery-outline{% else %}mdi:battery-{{(states.sensor.daryls_battery.state|float / 10)|round*10}}{%- endif %}"
    megans_battery_dyn:
      friendly_name: "Megan's XL"
      unit_of_measurement: "%"
      value_template: "{{states.sensor.megans_battery.state}}"
      icon_template: "{%- if states.sensor.megans_battery.state >= '95' %}mdi:battery{%- elif states.sensor.megans_battery.state == '100' %}mdi:battery{%- elif states.sensor.megans_battery.state <= '15' %}mdi:battery-outline{% else %}mdi:battery-{{(states.sensor.megans_battery.state|float / 10)|round*10}}{%- endif %}"