# # SmartThings Switches
# - platform: mqtt
  # name: "Porch Lights"
  # state_topic: "smartthings/Front Porch Lights/switch/state"
  # command_topic: "smartthings/Front Porch Lights/switch/cmd"
  # payload_on: "on"
  # payload_off: "off"
  # retain: true

# - platform: mqtt
  # name: "Bathroom Lights"
  # state_topic: "smartthings/Bathroom Lights/switch/state"
  # command_topic: "smartthings/Bathroom Lights/switch/cmd"
  # payload_on: "on"
  # payload_off: "off"
  # retain: true

# - platform: mqtt
  # name: "Bedroom Lights"
  # state_topic: "smartthings/Bedroom Lights/switch/state"
  # command_topic: "smartthings/Bedroom Lights/switch/cmd"
  # payload_on: "on"
  # payload_off: "off"
  # retain: true

# - platform: mqtt
  # name: "Landscaping Outlet"
  # state_topic: "smartthings/Landscaping Outlet/switch/state"
  # command_topic: "smartthings/Landscaping Outlet/switch/cmd"
  # payload_on: "on"
  # payload_off: "off"
  # retain: true

# - platform: mqtt
  # name: "Lamp"
  # state_topic: "smartthings/Peq Outlet/switch/state"
  # command_topic: "smartthings/Peq Outlet/switch/cmd"
  # payload_on: "on"
  # payload_off: "off"
  # retain: true

# Transmission Turtle
- platform: transmission
  host: !secret htpc_ip
  port: 428
  name: "Transmission Turtle"
  username: !secret transmission_user
  password: !secret transmission_pass

# Z-Wave Switches