# Transmission Turtle
# - platform: transmission
  # host: !secret htpc_ip
  # port: 428
  # name: "Transmission Turtle"
  # username: !secret transmission_user
  # password: !secret transmission_pass

# MQTT Switches - Sonoff
- platform: mqtt
  name: "Sonoff Cord 01"
  command_topic: "cmnd/sonoff01/POWER"
  state_topic: "stat/sonoff01/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: "true"

- platform: mqtt
  name: "Sonoff Cord 02"
  command_topic: "cmnd/sonoff02/POWER"
  state_topic: "stat/sonoff02/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: "true"

# - platform: template
  # switches:
    # garage_daryl:
      # value_template: '{% if is_state("sensor.daryls_garage_door", "closed") %}off{% else %}on{% endif %}'
      # turn_on:
        # service: script.turn_on
        # entity_id: script.trigger_daryls_garage_door
      # turn_off:
        # service: script.turn_on
        # entity_id: script.trigger_daryls_garage_door
      # entity_id: sensor.daryls_garage_door
      # friendly_name: "Daryl's Garage Door"

# - platform: template
  # switches:
    # garage_megan:
      # value_template: '{% if is_state("sensor.megans_garage_door", "closed") %}off{% else %}on{% endif %}'
      # turn_on:
        # service: script.turn_on
        # entity_id: script.trigger_megans_garage_door
      # turn_off:
        # service: script.turn_on
        # entity_id: script.trigger_megans_garage_door
      # entity_id: sensor.megans_garage_door
      # friendly_name: "Megan's Garage Door"