alias: "Tell the family it's 7:05"
trigger:
  platform: time
  # Military time format.
  at: '07:05:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: calendar.scheduling_nowork
      state: 'off'
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.smart_speakers
      volume_level: 0.75
  - service: media_player.play_media
    data:
      entity_id: media_player.smart_speakers
      #media_content_id: "https://hassio.s3.amazonaws.com/audio/harp-strumming-5s.mp3"
      media_content_id: '{{ ["https://hassio.s3.amazonaws.com/audio/harp-strumming-5s.mp3", "http://hassio.s3.amazonaws.com/audio/triumphal-fanfare-4s.mp3", "http://hassio.s3.amazonaws.com/audio/news-intro-5-25s.mp3"] | random }}'
      media_content_type: MUSIC
  - delay: 0:00:05
  - service: tts.google_say
    entity_id: media_player.smart_speakers
    data_template:
      message: >
        '{{ [
        "Good morning Henson family! Just wanted to let you know that it's 7:05. Have a great day!",
        "Good morning Daryl and Megan and Sawyer and Audrey and Hadley! Time to get ready!"
        "Hey everybody! It's 7:05. I hope you're ready for an awesome day!",
        "Yo. It's 5 after 7. Do stuff."
        ] | random }}'