alias: "Tell the family it's 7:10"
trigger:
  platform: time
  # Military time format.
  at: '07:10:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: calendar.scheduling_nowork
      state: 'off'
action:
  - service: media_player.play_media
    data:
      entity_id: media_player.smart_speakers
      media_content_id: "http://k003.kiwi6.com/hotlink/we2yvs4g3s/train-whistle-5s.mp3"
      media_content_type: MUSIC
  - delay: 0:00:05
  - service: tts.google_say
    entity_id: media_player.smart_speakers
    data_template:
      message: >
        '{{ ["Hey! It is seven ten! Better get a move on!", "Toot toot! 10 minutes after 7! Get going."] | random }}'