alias: "Tell the family it's 7:17"
trigger:
  platform: time
  # Military time format.
  at: '07:17:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: calendar.scheduling_nowork
      state: 'off'
action:
  - service: media_player.play_media
    data:
      entity_id: media_player.smart_speakers
      #media_content_id: "https://hassio.s3.amazonaws.com/audio/nuclear-warning-5s.mp3"
      media_content_id: '{{ ["https://hassio.s3.amazonaws.com/audio/sad-trombone-5s.mp3", "https://hassio.s3.amazonaws.com/audio/belch-5s.mp3", "https://hassio.s3.amazonaws.com/audio/1-person-yay-3s.mp3"] | random }}'
      media_content_type: MUSIC
  - delay: 0:00:5   
  - service: tts.google_say
    entity_id: media_player.smart_speakers
    data_template:
      message: >
        '{{ [
        "Looks like you're gonna be late. Might as well crack open a cold one and enjoy the lateness at this point.",
        "Welp, now you've done it. You're late. Good going.",
        "If you haven't listened to me before, you won't listen to me now, but... You're late, yo."
        ] | random }}'