alias: "Announce Daryl's Reminders"
trigger:
  platform: time
  # Military time format.
  at: '06:30:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: calendar.scheduling_nowork
      state: 'off'
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.master_bedroom_speaker
      volume_level: 0.75
  - service: media_player.play_media
    data:
      entity_id: media_player.master_bedroom_speaker
      media_content_id: "http://hassio.s3.amazonaws.com/audio/news-intro-5-25s.mp3"
      media_content_type: MUSIC
  - delay: 0:00:5
  - service: tts.google_say
    entity_id: media_player.master_bedroom_speaker
    data_template:
      message: "{{ states.input_text.reminder.state }}"