alias: "Bedroom Lights with Motion"
trigger:
  platform: state
  entity_id: sensor.bedroom_motion
  to: 'active'
condition:
  condition: state
  entity_id: input_boolean.sleepy_time_mode
  state: 'off'
action:
  service: switch.turn_on
  entity_id: switch.bedroom_switch