alias: "Bedroom No Motion"
trigger:
  platform: state
  entity_id: sensor.bedroom_motion
  to: 'inactive'
  for:
    minutes: 10
action:
  service: switch.turn_off
  entity_id: switch.bedroom_switch