alias: "Close Daryl's Door @ 11pm"
trigger:
  platform: time
  at: '23:00:00'
condition:
  condition: state
  entity_id: sensor.daryls_garage_door
  state: open
action:
  - service: switch.turn_off
    entity_id: switch.garage_daryl