alias: "Midnight"
trigger:
  platform: time
  at: '00:00:00'
action:
  - service: homeassistant.turn_off
    entity_id: group.off_at_midnight
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.sleepy_time_mode