alias: "Tell the family it's 7:05"
trigger:
  platform: time
  # Military time format.
  at: '07:05:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: calendar.scheduling_nowork
      state: 'off'
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.master_bedroom_speaker
      volume_level: 0.75
  - service: media_player.volume_set
    data:
      entity_id: media_player.kitchen_home
      volume_level: 0.75
  - service: tts.google_say
    entity_id: media_player.smart_speakers
    data:
      message: 'Hello. I just wanted to let you know that it is 7:05.'