alias: "Announce Daryl's Reminders"
trigger:
  platform: time
  # Military time format.
  at: '07:07:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: calendar.scheduling_nowork
      state: 'off'
action:
  service: tts.google_say
  entity_id: media_player.smart_speakers
  data:
    message: "{{ states.input_text.reminder.state }}"