##################################################################################
# Turns down the volume of my bedside GHome when Hadley would normally be in bed #
##################################################################################

alias: "GHome Quiet Time"
trigger:
  platform: time
  at: '20:00:00'
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.master_bedroom_speaker
      volume_level: 0.25