alias: "Tell the family it's 7:10"
trigger:
  platform: time
  # Military time format.
  at: '07:10:00'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: calendar.scheduling_nowork
      state: 'off'
action:
  - service: media_player.play_media
    data_template:
      entity_id: media_player.smart_speakers
      media_content_id: >
        '{{ ["/local/audio/school-bell-5s.mp3", "/local/audio/nuclear-warning-5s.mp3", "/local/audio/belch-5s.mp3"] | random }}'
      media_content_type: MUSIC
  - delay: 0:00:15   
  - service: tts.google_say
    entity_id: media_player.smart_speakers
    data:
      message: "It is 7:10, and time to leave. Have a good day!"