###########################################################
# Alerts Daryl that HQ is about to start, afternoon game  #
###########################################################

alias: "Notify Daryl when HQ is about to start (2pm)"
trigger:
  platform: time
  at: '14:00:00'
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  service: notify.html5
  data:
    message: "Go play! But you probably won't win."
    title: "It's HQ time!"
    target: "Daryl's 2XL"