########################################################################
# Sets Nest to away, turns off all lights but porch, notifies everyone #
########################################################################

alias: "Away Mode"
trigger:
  platform: state
  entity_id: binary_sensor.anyone_home
  to: 'off'
action:
  - service: nest.set_mode
    data:
      home_mode: away
  - service: homeassistant.turn_off
    entity_id: group.away_mode_off
  - service: notify.html5
    data:
      message: "Away mode enabled  at {{ as_timestamp(now()) | timestamp_custom('%I:%M', true) }} because nobody's home."
      title: "Roll Out!"