alias: "Early Morning Mode"
trigger:
  platform: sun
  event: sunrise
  offset: '-00:30:00'
action:
  - service: switch.turn_on
    entity_id: switch.porch_switch
  - service: light.turn_on
    entity_id: light.under_cabinet_lighting