#####################
# Sets Nest to home #
#####################

alias: "Home Mode"
trigger:
  platform: state
  entity_id: binary_sensor.anyone_home
  to: 'on'
action:
  - service: nest.set_mode
    data:
      home_mode: home