############################################################
# Turns on the porch light and sets frontend theme at dusk #
############################################################

alias: "Dusk Mode"
trigger:
  platform: sun
  event: sunset
  offset: '-00:30:00'
action:
  - service: switch.turn_on
    entity_id: switch.porch_switch
  # - service: switch.turn_on
    # entity_id: switch.sonoff_cord_02
  - service: frontend.set_theme
    data:
      name: dusk