alias: "Tell Daryl when Megan gets home"
trigger:
  platform: state
  entity_id: binary_sensor.megan_home
  to: 'on'
action:
  service: notify.html5
  data:
    message: "Safe and sound at {{ as_timestamp(now()) | timestamp_custom('%I:%M%p', true) }}"
    title: "Megan arrived home"
    target: "Daryl's 2XL"