#################################################
# Notify that SSL Certificate should renew soon #
#################################################

alias: "Notify Daryl that SSL cert should renew soon"
trigger: 
  platform: numeric_state
  entity_id: sensor.ssl_cert
  value_template: '{{ states.sensor.ssl_certificate_expiry.state }}'
  below: 32
action:
  service: notify.html5
  data: 
    message: "{{ as_timestamp(now()) | timestamp_custom('%I:%M%p', true) }} - Your SSL Certificate will expire in {{ states.sensor.ssl_certificate_expiry.state }} days."
    title: "SSL Cert Renewal Upcoming"
    target: "Daryl's XL"