############################################################
# Alerts Daryl that Megan is at Walmart, give him actions  #
############################################################

alias: "Tell Daryl when Megan is at Walmart"
trigger:
  platform: state
  entity_id: device_tracker.mixpix405_megans_xl
  to: 'Walmart'
action:
  service: notify.html5
  data:
    message: "Need anything? Tap yes, then update the list."
    title: "Megan is at Walmart"
    target: "Daryl's XL"
    data:
      actions:
        - action: "walmart_need_2"
          title: "Yes"
          icon: "/local/icons/checkbox-marked-circle-outline_hab.png"
        - action: "walmart_noneed"
          title: "Nope"
          icon: "/local/icons/close-circle-outline_hab.png"