#########################################################
# Notify Daryl if he leaves and his garage door is open #
#########################################################

alias: "Garage Open - Daryl"
trigger:
  platform: state
  entity_id: binary_sensor.daryl_home
  from: 'on'
condition:
  condition: state
  entity_id: sensor.daryl_garage_status
  state: open
action:
  - service: notify.html5
    data:
      message: "{{ as_timestamp(now()) | timestamp_custom('%I:%M', true) }}: You left your garage door open!"
      title: "Oops!"
      target: "Daryl's XL"
      data:
        actions:
          - action: "close_daryls_door"
            title: "Close it!"
            icon: mdi:garage