alias: "Tell Daryl when Megan gets home"
trigger:
  platform: state
  entity_id: binary_sensor.megan_home
  to: 'on'
action:
  service: notify.html5
  data:
    message: "safe and sound"
    title: "Megan arrived home"
    target: "Daryl's XL"