######################################################################
# Turns porch light on, if chosen, via actionable HTML5 notification #
######################################################################

alias: "Porch On via HTML5"
trigger:
  platform: event
  event_type: html5_notification.clicked
  event_data:
   action: button_on
action:
  service: switch.turn_on
  entity_id: switch.porch_switch