################################################################
# HTML5 notify Daryl that he's home, with action to tell Megan #
################################################################

alias: "Welcome Daryl home"
trigger:
  platform: state
  entity_id: binary_sensor.daryl_home
  from: 'off'
  to: 'on'
action:
  service: notify.html5
  data:
    message: "{{ as_timestamp(now()) | timestamp_custom('%I:%M%p', true) }} - Alert megan?"
    title: "Welcome home!"
    target: "Daryl's 2XL"
    data:
      actions:
        - action: "tell_her"
          title: "Sure..."
          icon: "/local/icons/human-female_hab.png"