#######################################################################
# Sets theme on startup, if  #
#######################################################################
alias: 'Set theme at startup'
initial_state: 'on'
trigger:
  platform: homeassistant
  event: start
condition:
  condition: state
  entity_id: sun.sun
  state: 'below_horizon'
action:
  service: frontend.set_theme
  data:
    name: dusk